version: '3.1'

services:

  working-assistant:
    image: working-assistant:${IMAGE_TAG}
    restart: always
    environment:
      STARTUP_ARGS: |
        --spring.datasource.url=jdbc:mysql://49.234.202.129/working_assistant?useUnicode=true&characterEncoding=UTF-8
        --spring.datasource.username=root
        --spring.datasource.password=3jIdgUnW0QvGkXiz
        --spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
    network_mode: bridge
    ports:
      - 8080:8080
    container_name: working-assistant